version: '3.9'

volumes:
  pg_data:

services:
  db:
    image: postgres:14.5
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - photo

  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: python /code/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - photo
  
networks:
  photo:
    driver: bridge