# Generated by Django 4.2.6 on 2023-10-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fyle_type', models.CharField(blank=True, choices=[('JPG', 'JPG'), ('WEBP', 'WEBP'), ('PNG', 'PNG'), ('GIF', 'GIF')], default='JPG', max_length=4, null=True, verbose_name='тип файла')),
                ('screen_resolution', models.CharField(blank=True, choices=[('400x300', '400x300'), ('600x450', '600x450'), ('800x600', '800x600'), ('1200x900', '1200x900'), ('1600x1200', '1600x1200')], default='800x600', max_length=9, null=True, verbose_name='разрешение экрана')),
                ('fon', models.CharField(blank=True, choices=[('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('TRANSPARENT', 'TRANSPARENT')], default='TRANSPARENT', max_length=11, null=True, verbose_name='фон')),
                ('scenario', models.CharField(blank=True, choices=[('VERTICAL', 'VERTICAL'), ('HORIZONTAL', 'HORIZONTAL'), ('SPIRAL', 'SPIRAL')], default='HORIZONTAL', max_length=10, null=True, verbose_name='сценарий съемки')),
                ('table_rotation', models.CharField(blank=True, choices=[('360', '360'), ('720', '720')], default='360', max_length=3, null=True, verbose_name='поворот стола')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='стоимость заказа')),
                ('shot_count', models.CharField(blank=True, choices=[('4', '4'), ('8', '8'), ('12', '12'), ('16', '16'), ('18', '18'), ('24', '24'), ('36', '36')], default='8', max_length=2, null=True, verbose_name='кол-во кадров')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercontent', to='content.content', verbose_name='контент')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercontent', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'Контент заказа',
                'verbose_name_plural': 'Контенты заказов',
            },
        ),
    ]
